### ISSUE TITLE
Zest Script Ignores followRedirects

### ISSUE THREAD

**Issue by B3B29F67** [zaproxy/zest#221]
Using ZAP 2.9.0 with Zest 32.0.0, it appears the followRedirects flag is being ignored (or I don't understand how it works).

I created this test script to demonstrate the issue:
```
{
  "about": "This is a Zest script. For more details about Zest visit https://developer.mozilla.org/en-US/docs/Zest",
  "zestVersion": "0.3",
  "title": "FollowRedirectsFalseNotWorking.zst",
  "description": "A template standalone script",
  "prefix": "",
  "type": "StandAlone",
  "parameters": {
    "tokenStart": "{{",
    "tokenEnd": "}}",
    "tokens": {},
    "elementType": "ZestVariables"
  },
  "statements": [
    {
      "url": "https://www.iana.org/domains/example",
      "data": "",
      "method": "GET",
      "headers": "",
      "assertions": [
        {
          "rootExpression": {
            "code": 301,
            "not": false,
            "elementType": "ZestExpressionStatusCode"
          },
          "elementType": "ZestAssertion"
        }
      ],
      "followRedirects": false,
      "timestamp": 0,
      "cookies": [],
      "index": 1,
      "enabled": true,
      "elementType": "ZestRequest"
    }
  ],
  "authentication": [],
  "index": 0,
  "enabled": true,
  "elementType": "ZestScript"
}
```

Despite the `followRedirects` flag being set to `false`, upon running the script, I assert (in this example) a stats code of 301 but it fails and I observe two entries in history:
https://www.iana.org/domains/example - 301
https://www.iana.org/domains/reserved - 200

I'm trying to build an authentication script, but need to capture the auth cookie only set in a 302 response. Despite setting the followRedirects to false, the script still follows the redirect. I'm not sure if it's a bug, or if I'm doing something incorrectly.

**Comment by thc202** [comment]
This as fixed in #216, it will be included in the next Zest release (and then updated in the ZAP add-on).
